### ISSUE TITLE
different 

### ISSUE THREAD

**Issue by drewskidang** [argilla-io/distilabel#304] opened 2024-01-28 17:03 UTC
can we use more than one model at once for the preference dataset generation

**Comment by dvsrepo** [comment] 2024-01-28 18:10
Yes! you should use LLMPool:

https://distilabel.argilla.io/latest/technical-reference/llms/#processllm-and-llmpool

There's some examples there but let us know if there's doubts

**Comment by drewskidang** [comment] 2024-01-28 20:34
Thank you!! i'm also having this error when i changed the generations from 2-3
![image](https://github.com/argilla-io/distilabel/assets/120294157/78b843cc-fae0-4f53-af76-3b4539216807)

**Comment by alvarobartt** [comment] 2024-01-29 07:48
Hi @drewskidang! Apparently that issue happens because during the `FeedbackDataset` creation in Argilla, those keys are not created, but then present on the records, so that it fails while trying to add the suggestions for those. Could you please send me script to reproduce? Thanks in advance 🤗

**Comment by drewskidang** [comment] 2024-01-30 06:09
thank you ... sorry but i can't find the notebook do you have  an example of uploading custom datasets?

**Comment by alvarobartt** [comment] 2024-01-30 07:36
Yes, indeed once the dataset has been generated via `Pipeline.generate` then only `to_argilla` is needed to convert the `datasets.Dataset` into `argilla.FeedbackDataset`, and to later upload it to Argilla `push_to_argilla`.

**Comment by alvarobartt** [comment] 2024-01-30 08:08
Oh fair, did you upload it to the HuggingFace Hub or somewhere? Also, what did you mean with `i'm also having this error when i changed the generations from 2-3`?

**Comment by drewskidang** [comment] 2024-01-30 08:14
The datasets i uploaded to huggingface i also have private jsonl files that i would like to annotate. I was following this example but changed  the code below

preference_dataset = preference_pipeline.generate(
    instructions_dataset,  # type: ignore
    num_generations=2, #### i change to 3 and i got the error 
    batch_size=8,
    display_progress_bar=True,
)

https://github.com/argilla-io/distilabel/blob/main/docs/tutorials/pipeline-notus-instructions-preferences-legal.ipynb

**Comment by drewskidang** [comment] 2024-01-30 11:13
would it be possible to get fireworkai intergration as well

**Comment by dvsrepo** [comment] 2024-01-30 11:25
> The datasets i uploaded to huggingface i also have private jsonl files that i would like to annotate.

@drewskidang reusing your dataset should be relatively straightforward, you should create a hf Dataset object and prepare the data in the format expected by the task in the distilabel Pipeline.

For example, if you want to use the PreferenceTask (for rating generations) you should create/rename a column as `generations` with a list of your LLM responses (the len of the list should be reflected with the num_generations arg when running pipeline.generate())

If you can share pseudo code or fake dataset examples and what you'd like to achieve we can guide you through

**Comment by drewskidang** [comment] 2024-01-30 12:02
no everything is working fine.. i just had the one bug when i changed the number of generations. You can close this now!

**Comment by gabrielmbmb** [comment] 2024-04-09 10:33
Hi @drewskidang, sorry for not replying earlier! We're about to release distilabel `1.0.0` and the API will change a bit, so we're closing issues related to the old version. Feel free to reopen the issue if you consider it.

**Closed by gabrielmbmb** 2024-04-09 10:33 UTC
