### ISSUE TITLE
[BUG] Develop branch hung when using replica > 2

### ISSUE THREAD

**Issue by zye1996** [argilla-io/distilabel#976] opened 2024-09-13 21:05 UTC
**Describe the bug**
I installed latest develop branch and run basic generation with StepResources(replica=8) and the generation hung. It does not happen to tags 88615c72182249203463401ec2f767e58ac84d9c

**To Reproduce**
Code to reproduce
```python

```

**Expected behaviour**

**Screenshots**

**Desktop (please complete the following information):**
 - Package version:
 - Python version:

**Additional context**

**Comment by gabrielmbmb** [comment] 2024-09-16 06:25
Hi @zye1996, thanks for reporting the issue. I'll check!

**Comment by gabrielmbmb** [comment] 2024-09-16 13:57
Hi again @zye1996! I confirmed that it gets hung. Just to confirm, at which moment of the execution of the pipeline do you see it gets hung? do you see that some replicas of the step finish?

**Comment by gabrielmbmb** [comment] 2024-09-16 14:13
we just merged a PR to `develop` that fixed one issue that made the pipeline hung just at the end of the execution because not all steps replicas were being unloaded. If you can try and confirm that your issue has been fixed would be awesome!

**Closed** 2024-10-08 15:28 UTC
Labels: bug
